import{a as S,S as b,i}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const w="51899291-b5c1abfe1ffa4d2b93e5576f4",q="https://pixabay.com/api/",v=15;async function E(r,o){const s={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:v};return(await S.get(q,{params:s})).data}const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),P=new b(".gallery a",{captionsData:"alt",captionDelay:250});function $(r){const o=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:t,views:a,comments:p,downloads:L})=>`
 <li>
 <a href="${n}">
 <img src="${s}" alt="${e}" />
 </a>
 <div class="info">
 <p>Likes: ${t}</p>
 <p>Views: ${a}</p>
 <p>Comments: ${p}</p>
 <p>Downloads: ${L}</p>
 </div>
 </li>
 `).join("");d.insertAdjacentHTML("beforeend",o),P.refresh()}function B(){d.innerHTML=""}function M(){f.classList.remove("hidden")}function A(){f.classList.add("hidden")}function O(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}const y=document.querySelector(".form"),x=document.querySelector(".load-more");let l=1,h="",c=0;y.addEventListener("submit",H);x.addEventListener("click",I);async function g(r,{reset:o=!1}={}){M(),u(),o&&B();try{const s=await E(h,r),{hits:n,totalHits:e}=s;if(r===1){if(c=e,n.length===0){i.error({title:"No results",message:"Sorry, there are no images matching your search query."});return}i.success({title:"Success",message:`We found ${c} images.`})}$(n);const t=document.querySelectorAll(".gallery li").length;t<c?O():t>=c&&r>1&&(u(),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{A()}}async function H(r){r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){i.error({title:"Error",message:"Please enter a search query!"});return}h=o,l=1,await g(l,{reset:!0}),y.reset()}async function I(){l+=1,await g(l),_()}function _(){const r=document.querySelector(".gallery li");if(!r)return;const{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
